service: dictionary-server
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
          Resource:
            - arn:aws:dynamodb:eu-central-1:343010466441:table/dictionary
            - arn:aws:dynamodb:eu-central-1:343010466441:table/dictionary/*

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
